export const SPEAR = 'CHANGE_SPEAR'
export const SHIELD = 'CHANGE_SHIELD'
export const SWORD = 'CHANGE_SWORD'
export const AXE = 'CHANGE_AXE'
export const READY = 'BATTLE_READY'
export const BATTLE = 'BATTLE_CALCULATION'
